# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-103c640d-b6c7-469e-bcd4-b22131d647ce";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-103c640d-b6c7-469e-bcd4-b22131d647ce".device = "/dev/disk/by-uuid/103c640d-b6c7-469e-bcd4-b22131d647ce";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1DB4-5FB9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-0d16854e-1a91-4a83-b2ac-38082eda095a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
