# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fd2b898f-3fc2-4e66-a16b-ed59f004b614";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-fd2b898f-3fc2-4e66-a16b-ed59f004b614".device = "/dev/disk/by-uuid/fd2b898f-3fc2-4e66-a16b-ed59f004b614";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-fd2b898f-3fc2-4e66-a16b-ed59f004b614";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-fd2b898f-3fc2-4e66-a16b-ed59f004b614";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7F2A-0712";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8efab24a-26a5-4e83-b382-90a775c3a795"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
