font_size 12.0

cursor                     #ccc
cursor_text_color          #111111
cursor_shape               block
cursor_shape_unfocused     hollow
cursor_blink_interval      -1
cursor_stop_blinking_after 15.0

cursor_trail 0
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_trail_color none

mouse_hide_wait -1

repaint_delay 10
input_delay 3
sync_to_monitor no

remember_window_size  yes
initial_window_width  640
initial_window_height 400

tab_bar_edge top
tab_bar_margin_width 1.0
# Make custom with python?
tab_bar_style fade
tab_bar_min_tabs 1
tab_title_max_length 32
tab_title_template "{index} {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

active_tab_foreground   #0f0
active_tab_background   #303446
active_tab_font_style   normal
inactive_tab_foreground #fff
inactive_tab_background #444
inactive_tab_font_style normal

tab_bar_background #181825
tab_bar_margin_color #181825

foreground #fff
background #000
background_opacity 0.75
dynamic_background_opacity no

startup_session none
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
term xterm-kitty
linux_display_server auto

kitty_mod alt
clear_all_shortcuts yes
map_timeout 0.0

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map kitty_mod+p scroll_page_up
map kitty_mod+n scroll_page_down

map kitty_mod+w new_window
map kitty_mod+q close_window

map kitty_mod+] next_window
map kitty_mod+[ previous_window

map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+0 goto_tab 10

map kitty_mod+right next_tab
map kitty_mod+left previous_tab
map kitty_mod+c new_tab
map kitty_mod+shift+q close_tab

map kitty_mod+equal  change_font_size all +2.0
map kitty_mod+plus   change_font_size all +2.0
map kitty_mod+kp_add change_font_size all +2.0
map kitty_mod+minus       change_font_size all -2.0
map kitty_mod+kp_subtract change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0

map kitty_mod+m command_palette

map kitty_mod+enter toggle_fullscreen

map kitty_mod+a>m set_background_opacity +0.1
map kitty_mod+a>l set_background_opacity -0.1

map kitty_mod+f5 load_config_file
map kitty_mod+f6 debug_config


# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
