# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-cb9b892b-8538-4a2a-b343-f16cdba97e53";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cb9b892b-8538-4a2a-b343-f16cdba97e53".device = "/dev/disk/by-uuid/cb9b892b-8538-4a2a-b343-f16cdba97e53";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2BF0-3156";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ea0ea4e6-9c37-4f62-a3b0-a728f149f085"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
